function jsFetchNum(id: string): Promise<number> {
    //code ...
    //code ...
    //code ...
    //code ...
    //code ...
    return new Promise((resolve:Number, reject : boolean) => {
        resolve(100);
    });
}